apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dp.name }}
  labels:
    app: {{ .Values.tagValue }}
spec:
  replicas: {{ .Values.dp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.tagValue }}
  template:
    metadata:
      labels:
        app: {{ .Values.tagValue }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.imageUrl }}
        ports:
        - containerPort: {{ .Values.container.port }}
        env:
        - name: {{ .Values.configMap.sqlUrlName }}                 
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }} 
              key: {{ .Values.configMap.sqlUrlName }} 

        - name: {{ .Values.configMap.funcUrlName }}                 
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }} 
              key: {{ .Values.configMap.funcUrlName }}  

        - name: {{ .Values.configMap.appUrlName }}                 
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }} 
              key: {{ .Values.configMap.appUrlName }} 

        - name: {{ .Values.configMap.funcCodeName }}                 
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }} 
              key: {{ .Values.configMap.funcCodeName }}       

        - name: {{ .Values.configMap.sqlName }}                 
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }} 
              key: {{ .Values.configMap.sqlName }}   

        - name: {{ .Values.configMap.sqlPasswordName }}                 
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }} 
              key: {{ .Values.configMap.sqlPasswordName }}              

        - name: {{ .Values.configMap.sqlUsernameName }}                 
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }} 
              key: {{ .Values.configMap.sqlUsernameName }}         

