trigger:
  paths:
    include:
    - aks-pipeline.yml
    - content/aks-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template:   stages\vars\vars.yml  
stages:
#calling the sql-stage to import the database to azure


- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(aksResourceGroupName)
    tagValue:  $(tagValue)
    resoucType: $(acrResourceType)
    StageName: "Get_Acr_info"


- template: 'stages\aks-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    resourceGroupName: $(aksResourceGroupName)
    appImageName: $(appImageName)
    prometheusExporterImageName: $(prometheusExporterImageName)
    StageName: "Get_Acr_info"