trigger:
  paths:
    include:
    - aks-pipeline.yml
    - content/aks-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template:   stages\vars\vars.yml  
stages:
#calling the sql-stage to import the database to azure


- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(aksResourceGroupName)
    tagValue:  $(tagValue)
    StageName: "Get_Aks_Info"
    


- template: 'stages\aks-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    resourceGroupName: $(aksResourceGroupName)
    appImageName: $(appImageName)
    prometheusExporterImageName: $(prometheusExporterImageName)
    StageName: "Get_Aks_Info"
    dependsOn: "Get_Aks_Info"
    appImageVersion: $(appImageVersion)
    deploy: ${{variables.deployAks}}
    ingressHostname: $(ingressHostname)
    deployGrafana: ${{variables.deployGrafana}}
    sqlPassword: $(sqlPassword)
    sqlUserName: $(sqlUserName)
    databaseName: $(databaseName)
       port: $(appPort)
    appImageVersion: $(appImageVersion)