#The triggers for the pipeline
trigger:
  paths:
    include:
    - aks-pipeline.yml
    - content/aks-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template:   stages\vars\vars.yml  
stages:


#Calling the Get_Aks_Info stage to retrieve the necessary data for the deployment of the Aks
- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(aksResourceGroupName)
    tagValue:  $(tagValue)
    StageName: "Get_Aks_Info"
    

#Calling the Deploy_K8s_Content stage to set the vars needed for the Aks to connect with the other resources and deploy the content of the Aks inside it
- template: 'stages\aks-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    resourceGroupName: $(aksResourceGroupName)
    appImageName: $(appImageName)
    prometheusExporterImageName: $(prometheusExporterImageName)
    StageName: "Get_Aks_Info"
    dependsOn: "Get_Aks_Info"
    appImageVersion: $(appImageVersion)
    deploy: ${{variables.deployAks}}
    ingressHostname: $(ingressHostname)
    deployGrafana: ${{variables.deployGrafana}}
    sqlPassword: $(sqlPassword)
    sqlUserName: $(sqlUserName)
    databaseName: $(databaseName)
    port: $(appPort)