trigger:
  paths:
    include:
    - aks-pipeline.yml
    - content/aks-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template:   pipelines\vars\vars.yml  
stages:
#calling the sql-stage to import the database to azure
- template: 'pipelines\aks-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    tagValue: $(tagValue)
    resourceGroupName: $(aksResourceGroupName)
    appImageName: $(appImageName)
    prometheusExporterImageName: $(prometheusExporterImageName)