# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none
variables:
  # Azure Resource Manager connection created during pipeline creation
  #azureServiceConnectionId: 'ad39f181-531d-47fd-b9dc-1b0488bcaa1d'
  - template:  pipelines\vars\vars.yml  
pool:
  vmImage: ubuntu-latest
stages:
- template: 'pipelines\infraestructure-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)

- template: 'pipelines\webapp-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    webAppName: $(webAppName)
    pythonVersion: $(pythonVersion)
    dependsOn: deploy_infrastructure
    
- template: 'pipelines\function-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    functionAppName: $(functionAppName)
    pythonVersion: $(pythonVersion)
    dependsOn: deploy_infrastructure

  