# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


variables:
  # Azure Resource Manager connection created during pipeline creation
  #azureServiceConnectionId: 'Service_connection'
  - template:  pipelines\vars\vars.yml  
pool:
  #vmImage: ubuntu-latest
  vmImage: windows-latest
stages:

- template: 'pipelines\aks-permissions-stage.yml'
  condition: eq( "$(useAksMonitoring)" , 'true')
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    useAksMonitoring: $(useAksMonitoring)
    #dependsOn: deploy_infrastructure