# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- bicep-version

pool:
  vmImage: ubuntu-latest

variables:
- template:   pipelines\vars\vars.yml  

steps:

- task: HelmInstaller@0
  inputs:
    helmVersion: '2.14.1'
    installKubectl: true
    
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build ./content/aks-content -t $(repositoracrRepositoryNameyName)
      az aks get-credentials --name $(aksclusterName) --resource-group $(aksResourceGroupName)
      helm create new-chart
      helm install new-chart new-chart/

