# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- bicep-version

pool:
  vmImage: windows-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(2c02e9f9-7fad-4208-82e1-4e97500b5e0e)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd ./content/function-content
      func azure functionapp publish 'proj-dev-func' --no-bundler
