# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure para estudiantes(b5621309-22cd-4fc5-930c-dabc2c4c9ae7)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment create --location "West Europe" --name "rg1" --template-file .\arm-azure-template.json'
    workingDirectory: '$(system.defaultworkingdirectory)'