# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  paths:
    include:
    - azure-pipelines.yml
    - main.bicep
    - bicep-templates/*

variables:
  # Azure Resource Manager connection created during pipeline creation
  #azureServiceConnectionId: 'Service_connection'
  - template:  pipelines\vars\vars.yml  
pool:
  #vmImage: ubuntu-latest
  vmImage: windows-latest
stages:
- template: 'pipelines\infraestructure-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)


- template: 'pipelines\webapp-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    webAppName: $(webAppName)
    pythonVersion: $(pythonVersion)
    dependsOn: deploy_infrastructure
    
- template: 'pipelines\function-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    functionAppName: $(functionAppName)
    pythonVersion: $(pythonVersion)
    dependsOn: deploy_infrastructure

- template: 'pipelines\aks-permissions-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    useAksMonitoring: $(useAksMonitoring)
    dependsOn: deploy_infrastructure

- template: 'pipelines\aks-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    acrUrl: $(acrUrl)
    resourceGroupName: $(aksResourceGroupName)
    appImageName: $(appImageName)
    prometheusExporterImageName: $(prometheusExporterImageName)
    dependsOn: set_aks_permissions
  
- template: 'pipelines\sql-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    serverName: $(sqlServerName)
    DatabaseName: $(databaseName)
    Username: $(sqlUserName)
    Password: $(sqlPassword)
    serverFqdn: $(sqlServerFqdn)
    resourceGroupName: $(sqlResourceGroupName)
    dependsOn: deploy_infrastructure
  