trigger:
  paths:
    include:
    - function-pipeline.yml
    - content/function-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template: stages\vars\vars.yml  

stages:

- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(funcResourceGroupName)
    tagValue:  $(tagValue)
    StageName: "Get_Function_Info"

- template: 'stages\function-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    StageName: "Get_Function_Info"
    resourceGroup: $(funcResourceGroupName)
    deploy: ${{variables.deployFunc}}



- template: 'stages\set-function-vars.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    StageName: "Get_Function_Info"
    resourceGroup: $(funcResourceGroupName)
    dependsOn:  Deploy_Function_Content
    deploy: ${{variables.deployFunc}}
    sqlPassword: $(sqlPassword)
    sqlUserName: $(sqlUserName)
    databaseName: $(databaseName)
    aksUrl: $(ingressHostname)
