trigger:
  paths:
    include:
    - function-pipeline.yml
    - content/function-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template: pipelines\vars\vars.yml  
stages:
- template: 'pipelines\function-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    functionAppName: $(functionAppName)
    pythonVersion: $(pythonVersion)
    #dependsOn: deploy_infrastructure