trigger:
  paths:
    include:
    - function-pipeline.yml
    - content/function-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template: stages\vars\vars.yml  

stages:

- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(funcResourceGroupName)
    tagValue:  $(tagValue)
    resoucType: $(siteResourceType)
    StageName: "Get_Fun_Name"

- template: 'stages\function-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    StageName: "Get_Fun_Name"

