#The triggers for the pipeline
trigger:
  paths:
    include:
    - function-pipeline.yml
    - content/function-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template: stages\vars\vars.yml  

stages:

#Calling the Get_Function_Info stage to retrieve the necessary data for the deployment of the Azure Function content and for the enviorments vars
- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(funcResourceGroupName)
    tagValue:  $(tagValue)
    StageName: "Get_Function_Info"

#Calling the Deploy_Function_Content stage to deploy the content of the Azure Function inside it
- template: 'stages\function-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    StageName: "Get_Function_Info"
    resourceGroup: $(funcResourceGroupName)
    deploy: ${{variables.deployFunc}}

#Calling the Add_Function_Env_Vars stage to set the vars needed for the Azure Function to connect with the other resources
- template: 'stages\set-function-vars.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    StageName: "Get_Function_Info"
    resourceGroup: $(funcResourceGroupName)
    dependsOn:  Deploy_Function_Content
    deploy: ${{variables.deployFunc}}
    sqlPassword: $(sqlPassword)
    sqlUserName: $(sqlUserName)
    databaseName: $(databaseName)
    aksUrl: $(ingressHostname)
