# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none

variables:
  # Azure Resource Manager connection created during pipeline creation
  #azureServiceConnectionId: 'Service_connection'
  - template:  pipelines\vars\vars.yml  



stages:

- stage: STAGE_X
  pool:
    vmImage: windows-latest
  jobs:
  - job: STAGE_X_JOB_A
    steps:
    - checkout: none
    - task: AzureCLI@2
      name: ValidateVar
      inputs:
        azureSubscription: 'Service_connection'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "This is job STAGE_X_JOB_A. Lets set the value"
                  PARAM_X="TEST"
                  echo "##vso[task.setvariable variable=VarKey;isOutput=true]$PARAM_X"
                      
  
- stage: STAGE_Y
  pool:
    vmImage: ubuntu-latest
  dependsOn: STAGE_X
  jobs:
  - job: STAGE_Y_JOB_B
    variables:
      varFromStageA: $[ stageDependencies.STAGE_X.STAGE_X_JOB_A.outputs['ValidateVar.VarKey'] ]
    steps:
    - checkout: none
    - script: |
        echo "This Job will print value from Stage STAGE_X"
        echo $(varFromStageA)