# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none

variables:
  # Azure Resource Manager connection created during pipeline creation
  #azureServiceConnectionId: 'Service_connection'
  - template:  pipelines\vars\vars.yml  
pool:
  vmImage: ubuntu-latest


stages:

- stage: STAGE_X
  jobs:
  - job: STAGE_X_JOB_A
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Service_connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "This is job STAGE_X_JOB_A. Lets set the value"
          export PARAM_X=$(ls)
          echo $(PARAM_X)
          echo "$(PARAM_X)"
          echo "$PARAM_X"
          echo $PARAM_X
          echo ${PARAM_X}
          echo "${PARAM_X}"
          echo "PARAM_X"
      name: ValidateVar

    
  
- stage: STAGE_Y
  dependsOn: STAGE_X
  jobs:
  - job: STAGE_Y_JOB_B
    variables:
      varFromStageA: $[ stageDependencies.STAGE_X.STAGE_X_JOB_A.outputs['ValidateVar.VarKey'] ]
    steps:
    - checkout: none
    - script: |
        echo "This Job will print value from Stage STAGE_X"
        echo $(varFromStageA)