# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  paths:
    include:
    - principal-pipeline.yml
    - bicep-templates/*
    - main.bicep
    - bicep-templates

variables:
  # Azure Resource Manager connection created during pipeline creation
  #azureServiceConnectionId: 'Service_connection'
  - template:  pipelines\vars\vars.yml  
pool:
  #vmImage: ubuntu-latest
  vmImage: windows-latest
stages:
- template: 'pipelines\infraestructure-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)

- template: 'pipelines\get-name-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(appResourceGroupName)
    tagValue:  $(tagValue)
    resoucType: $(siteResourceType)
    StageName: "Get_App_Name"
    dependsOn: Deploy_Infrastructure

- template: 'pipelines\webapp-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    stageName: "Get_App_Name"
    
    
- template: 'pipelines\get-name-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(funcResourceGroupName)
    tagValue:  $(tagValue)
    resoucType: $(siteResourceType)
    StageName: "Get_Fun_Name"
    dependsOn: Deploy_Infrastructure

- template: 'pipelines\function-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    StageName: "Get_Fun_Name"


- template: 'pipelines\aks-permissions-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    useGrafana: $(useGrafana)
    dependsOn: Deploy_Infrastructure

- template: 'pipelines\aks-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    tagValue: $(tagValue)
    resourceGroupName: $(aksResourceGroupName)
    appImageName: $(appImageName)
    prometheusExporterImageName: $(prometheusExporterImageName)
    dependsOn: Set_Aks_Permissions
  
- template: 'pipelines\get-name-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(appResourceGroupName)
    tagValue:  $(tagValue)
    resoucType: $(siteResourceType)
    StageName: "Get_App_Name"
    dependsOn: Deploy_Infrastructure

- template: 'pipelines\sql-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    databaseName: $(aksclusterName)
    userName: $(acrUrl)
    resourceGroupName: $(sqlResourceGroupName)
    password: $(repositoracrRepositoryNameyName)
    StageName: "Get_App_Name"