# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  paths:
    include:
    - principal-pipeline.yml
    - bicep-templates/*
    - main.bicep
    - bicep-templates

variables:
  # Azure Resource Manager connection created during pipeline creation
  #azureServiceConnectionId: 'Service_connection'
  - template:  stages\vars\vars.yml  
pool:
  #vmImage: ubuntu-latest
  vmImage: windows-latest
stages:
- template: 'stages\infraestructure-stage.yml'


- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(appResourceGroupName)
    tagValue:  $(tagValue)
    StageName: "Get_Inicial_Info"
    dependsOn2: Deploy_Infrastructure
    dependsOn: Deploy_Infrastructure


- template: 'stages\webapp-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    stageName: "Get_Inicial_Info"
    resourceGroup: $(appResourceGroupName)
    deploy: ${{variables.deployApp}}

    

- template: 'stages\function-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    StageName: "Get_Inicial_Info"
    resourceGroup: $(funcResourceGroupName)

- template: 'stages\aks-permissions-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    useGrafana: $(useGrafana)
    dependsOn: Deploy_Infrastructure

- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(aksResourceGroupName)
    tagValue:  $(tagValue)
    StageName: "Get_Aks_Info"
    dependsOn: Deploy_Function_Content
    dependsOn2: Deploy_Webapp_Content

- template: 'stages\aks-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    resourceGroupName: $(aksResourceGroupName)
    appImageName: $(appImageName)
    prometheusExporterImageName: $(prometheusExporterImageName)
    StageName: "Get_Aks_Info"
    dependsOn: 'Set_Aks_Permissions'
    ingressHostname: $(ingressHostname)
  

- template: 'stages\sql-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    DatabaseName: $(databaseName)
    Username: $(sqlUserName)
    Password: $(sqlPassword)
    resourceGroupName: $(sqlResourceGroupName)
    StageName: "Get_Inicial_Info"


- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(appResourceGroupName)
    tagValue:  $(tagValue)
    StageName: "Get_Apps_Info"
    dependsOn2: Deploy_K8s_Content
    dependsOn:  Deploy_K8s_Content

- template: 'stages\set-function-vars.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    StageName: "Get_Apps_Info"
    resourceGroup: $(funcResourceGroupName)
    dependsOn:  Get_Apps_Info


- template: 'stages\set-webapp-vars.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    StageName: "Get_Apps_Info"
    resourceGroup: $(appResourceGroupName)
    dependsOn:  Get_Apps_Info