# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  paths:
    include:
    - principal-pipeline.yml
    - bicep-templates/*
    - main.bicep
    - bicep-templates

variables:
  # Azure Resource Manager connection created during pipeline creation
  #azureServiceConnectionId: 'Service_connection'
  - template:  stages\vars\vars.yml  
pool:
  #vmImage: ubuntu-latest
  vmImage: windows-latest
stages:
- template: 'stages\infraestructure-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)

- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(appResourceGroupName)
    tagValue:  $(tagValue)
    resoucType: $(siteResourceType)
    StageName: "Get_Inicial_Info"


- template: 'stages\webapp-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    stageName: "Get_Inicial_Info"
    resourceGroup: $(appResourceGroupName)
    

- template: 'stages\function-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    StageName: "Get_Inicial_Info"
    resourceGroup: $(funcResourceGroupName)

- template: 'stages\aks-permissions-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    useGrafana: $(useGrafana)
    dependsOn: Deploy_Infrastructure

- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(aksResourceGroupName)
    tagValue:  $(tagValue)
    resoucType: $(acrResourceType)
    StageName: "Get_Aks_Info"
    dependsOn: [Deploy_Function_Content,Deploy_Webapp_Content]

- template: 'stages\aks-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    aksclusterName: $(aksclusterName)
    resourceGroupName: $(aksResourceGroupName)
    appImageName: $(appImageName)
    prometheusExporterImageName: $(prometheusExporterImageName)
    StageName: "Get_Aks_Info"
    dependsOn: 'Set_Aks_Permissions'
  
#- template: 'stages\get-info-stage.yml'
#  parameters:
#    azureSubscription: $(azureSubscription)
#    resourceGroup: $(sqlResourceGroupName)
#    tagValue:  $(tagValue)
#    resoucType: $(sqlResourceType)
#    StageName: "Get_Sql_Info"
#    dependsOn: Deploy_Infrastructure


- template: 'stages\sql-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    DatabaseName: $(databaseName)
    Username: $(sqlUserName)
    Password: $(sqlPassword)
    resourceGroupName: $(sqlResourceGroupName)
    StageName: "Get_Inicial_Info"