#parameters:
#- name: databaseName
#  type: string
#  default: 'proj-dev-sqldb'

#- name: sqlUserName
#  type: string
#  default: 'omar1'

#- name: sqlPassword
#  type: string
#  default: 'Kassar@14689'

#- name: azureSubscription
#  type: string
#  default: 'Azure subscription 1(2c02e9f9-7fad-4208-82e1-4e97500b5e0e)'

#- name: sqlServerName
#  type: string
#  default: 'proj-dev-sql'

trigger: none

pool:
  vmImage: ubuntu-latest
variables:
- template:   /pipelines/vars/Sche/vars.yml  
stages:
- template: 'pipelines\sql-stage.yml'
  parameters:
    azureSubscription: '${{azureSubscription}}'
    sqlServerName: $(sqlServerName)
    DatabaseName: $(databaseName)
    SqlUsername: $(sqlUserName)
    SqlPassword: $(sqlPassword)
    DacpacFile: $(DacpacFile)