trigger:
  paths:
    include:
    - sql-pipeline.yml
    - content/sql-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template: stages\vars\vars.yml  
stages:
#calling the sql-stage to import the database to azure


- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(sqlResourceGroupName)
    tagValue:  $(tagValue)
    resoucType: $(sqlResourceType)
    StageName: "Get_Sql_Info"


- template: 'stages\sql-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    DatabaseName: $(databaseName)
    Username: $(sqlUserName)
    Password: $(sqlPassword)
    resourceGroupName: $(sqlResourceGroupName)
    StageName: "Get_Sql_Info"