#The triggers for the pipeline
trigger:
  paths:
    include:
    - sql-pipeline.yml
    - content/sql-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template: stages\vars\vars.yml  
stages:


#Calling the Get_Sql_Info stage to retrieve the necessary data for the deployment of the Azure Sql content
- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(sqlResourceGroupName)
    tagValue:  $(tagValue)
    StageName: "Get_Sql_Info"

#Calling the Deploy_Sql_Content stage to deploy the Sql database content inside the Azure Sql resource
- template: 'stages\sql-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    DatabaseName: $(databaseName)
    Username: $(sqlUserName)
    Password: $(sqlPassword)
    resourceGroupName: $(sqlResourceGroupName)
    StageName: "Get_Sql_Info"
    deploy: ${{variables.deploySql}}