trigger:
  paths:
    include:
    - webapp-pipeline.yml
    - content/webapp-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template: pipelines\vars\vars.yml  
stages:

- template: 'pipelines\get-name-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(appResourceGroupName)
    tagValue:  $(tagValue)
    resoucType: "microsoft.web/sites"
    StageName: "Get_App_Name"

- template: 'pipelines\webapp-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(appResourceGroupName)
    pythonVersion: $(pythonVersion)
    stageName: "Get_App_Name"