trigger:
  paths:
    include:
    - webapp-pipeline.yml
    - content/webapp-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template: stages\vars\vars.yml  
stages:

- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(appResourceGroupName)
    tagValue:  $(tagValue)
    StageName: "Get_App_Info"

- template: 'stages\webapp-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    stageName: "Get_App_Info"
    resourceGroup: $(appResourceGroupName)