trigger:
  paths:
    include:
    - webapp-pipeline.yml
    - content/webapp-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template: stages\vars\vars.yml  
stages:

- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(appResourceGroupName)
    tagValue:  $(tagValue)
    StageName: "Get_Webapp_Info"

- template: 'stages\webapp-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    stageName: "Get_Webapp_Info"
    resourceGroup: $(appResourceGroupName)
    deploy: ${{variables.deployApp}}


- template: 'stages\set-webapp-vars.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    StageName: "Get_Webapp_Info"
    resourceGroup: $(appResourceGroupName)
    dependsOn:  Deploy_Webapp_Content
    deploy: ${{variables.deployApp}}
    sqlPassword: $(sqlPassword)
    sqlUserName: $(sqlUserName)
    databaseName: $(databaseName)