trigger: none
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template:   pipelines\vars\vars.yml  
stages:
#calling the sql-stage to import the database to azure
- template: 'pipelines\webapp-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    webAppName: $(webAppName)
    pythonVersion: $(pythonVersion)
    dependsOn: deploy_infrastructure