trigger:
  paths:
    include:
    - webapp-pipeline.yml
    - content/webapp-content/*
pool:
  vmImage: windows-latest
#load vars from the vars.yml file
variables:
- template: stages\vars\vars.yml  
stages:

#Calling the Get_Webapp_Info stage to retrieve the necessary data for the deployment of the Azure Webapp content and the enviorments vars
- template: 'stages\get-info-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    resourceGroup: $(appResourceGroupName)
    tagValue:  $(tagValue)
    StageName: "Get_Webapp_Info"

#Calling the Deploy_Webapp_Content stage to deploy the content of the Azure Function inside it
- template: 'stages\webapp-stage.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    pythonVersion: $(pythonVersion)
    stageName: "Get_Webapp_Info"
    resourceGroup: $(appResourceGroupName)
    deploy: ${{variables.deployApp}}

#Calling the Add_Webapp_Env_Vars stage to set the vars needed for the Azure Function to connect with the other resources
- template: 'stages\set-webapp-vars.yml'
  parameters:
    azureSubscription: $(azureSubscription)
    StageName: "Get_Webapp_Info"
    resourceGroup: $(appResourceGroupName)
    dependsOn:  Deploy_Webapp_Content
    deploy: ${{variables.deployApp}}
    sqlPassword: $(sqlPassword)
    sqlUserName: $(sqlUserName)
    databaseName: $(databaseName)
    aksUrl: $(ingressHostname)