
parameters:
- name: azureSubscription
  type: string
  default: 'Azure subscription 1(2c02e9f9-7fad-4208-82e1-4e97500b5e0e)'

- name: acrName
  type: string 
  default: 'projcr22er'
trigger: none


stages:

- stage: Build
  vmImageName: 'ubuntu-latest'
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '${{parameters.acrName}}'
        repository: 'python'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    - task: Docker@2
      inputs:
        containerRegistry: '${{parameters.acrName}}'
        repository: "python"
        command: 'push'
        Dockerfile: 'Dockerfile'
        buildContext: 
 