parameters:
- name: azureSubscription
  type: string
  #default: 'Azure subscription 1(2c02e9f9-7fad-4208-82e1-4e97500b5e0e)'
  
- name: aksclusterName
  type: string 
  #default: 'aks'
  
- name: acrUrl
  type: string
  #default: 'projdevacr.azurecr.io' 
  

- name: resourceGroupName
  type: string 
  #default: 'proj-dev-app-rg'

- name: repositoryName  
  type: string
  #default: proj

- name: dependsOn
  type: string
  default: ''  

stages:
- stage: deploy_k8s_content
  displayName: create and push kubernetes content
  dependsOn: ${{parameters.dependsOn}}
  jobs:
  - job: deploy_k8s_content
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
      - task: HelmInstaller@0
        inputs:
          helmVersion: '2.14.1'
          installKubectl: false
      - task: AzureCLI@2
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }} 
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            docker build ./content/aks-content -t ${{parameters.repositoryName}}
            az aks get-credentials --name ${{parameters.aksclusterName}} --resource-group ${{parameters.resourceGroupName}}
            az acr login --name ${{parameters.acrUrl}}
            docker tag "${{parameters.repositoryName}}:latest" '${{parameters.acrUrl}}'"/${{parameters.repositoryName}}:latest"
            docker image ls
            docker push '${{parameters.acrUrl}}'"/${{parameters.repositoryName}}:latest"
            kubectl delete --all deployment --namespace=default
            kubectl apply -f ./content/aks-content/dp.yml
            kubectl apply -f ./content/aks-content/svc.yml
            kubectl get svc 
            kubectl create ns monitoring 
            kubectl create ns ingress-ngnix
            output=$(helm list -A)         
            if [[ "$output" == *"grafana"* ]]; then    
              helm update -n monitoring grafana ./content/aks-content/kube-prometheus-stack
             else
              helm install -n monitoring grafana ./content/aks-content/kube-prometheus-stack
            fi 
            if [[ "$output" == *"ingress-ngnix"* ]]; then 
              helm update -n ingress-ngnix ingress ./content/aks-content/ingress-ngnix
            else
              helm install -n ingress-ngnix ingress ./content/aks-content/ingress-ngnix
            fi

