#parameters:
#- name: azureSubscription
#  type: string
  #default: 'Azure subscription 1(2c02e9f9-7fad-4208-82e1-4e97500b5e0e)'
  


stages:
- stage: get_resource_name
  displayName: Get azure resource name
  jobs:
  - job: get_resource_name
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: PowerShell@2
        displayName: 'Get azure resource name'
        name: Getname
        inputs:
          targetType: inline
          script: |
            $kubeletPrincipalId = "omar"

            Write-Host "kubeletPrincipalId:"
            Write-Host $kubeletPrincipalId

            Write-Host "##vso[task.setvariable variable=kubeletPrincipalId;isOutput=true]$kubeletPrincipalId"