
parameters:
- name: databaseName
  type: string
  
- name: DacpacFile
  type: string

- name: sqlUserName
  type: string

- name: sqlPassword
  type: string

- name: azureSubscription
  type: string

- name: sqlServerName
  type: string

stages:
- stage: deploy_sql_content
  jobs :
  - job: import_sql_database_to_sqlServer
    steps:
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: ${{azureSubscription}}
        ServerName: $(sqlServerName)
        DatabaseName: $(databaseName)
        SqlUsername: $(sqlUserName)
        SqlPassword: $(sqlPassword)
        DacpacFile: 'content\sql-content\proj-dev-sqldb-2022-4-21-17-56.bacpac'