
parameters:
- name: databaseName
  type: string
  

- name: userName
  type: string

- name: password
  type: string

- name: azureSubscription
  type: string

- name: SERVERNAME
  type: string

- name: resourceGroupName
  type: string  

- name: serverFqdn
  type: string


stages:
#import the bacpac file database
- stage: deploy_sql_content
  jobs :
  - job: import_sql_database_to_sqlServer
    steps:
    - powershell: |
          Write-Host "You can use macro syntax for variables: $(SERVERNAME)"

    - task: AzurePowerShell@5
      displayName: open sql server firewall
      inputs:
        azureSubscription: '$(azureSubscription)'
        ScriptPath: 'content\sql-content\set-azure-firewall-rule.ps1'
        ScriptArguments: "-ServerName $(SERVERNAME) -ResourceGroup 'proj-dev-sql-rg"
        azurePowerShellVersion: LatestVersion


    - task: CmdLine@1
      displayName: Run Sqlcmd
      inputs:
        filename: 'Sqlcmd'
        arguments: "-S '$(serverFqdn)' -U '$(userName)' -P '$(password)' -d '$(databaseName)' -i 'content\\sql-content\\database.sql'"

    - task: AzurePowerShell@5
      displayName: close sql server firewall
      inputs:
        azureSubscription: '$(azureSubscription)'
        ScriptPath: 'content\sql-content\remove-azure-firewall.ps1'
        ScriptArguments: "'$(serverName)' -ResourceGroup '$(resourceGroupName)'"
        azurePowerShellVersion: LatestVersion



    
  #  - task: SqlAzureDacpacDeployment@1
  #    inputs:
  #      azureSubscription: $(azureSubscription)
  #      ServerName: $(serverName)
  #      DatabaseName: $(databaseName)
  #      SqlUsername: $(userName)
  #      SqlPassword: $(password)
  #      DacpacFile: 'content\sql-content\proj-dev-sqldb-2022-4-21-17-56.bacpac'