
parameters:
- name: databaseName
  type: string
  

- name: userName
  type: string

- name: password
  type: string

- name: azureSubscription
  type: string

- name: SERVERNAME
  type: string

- name: resourceGroupName
  type: string  

- name: serverFqdn
  type: string


stages:
#import the bacpac file database
- stage: deploy_sql_content
  jobs :
  - job: import_sql_database_to_sqlServer
    steps:
    - task: AzurePowerShell@5
      displayName: open sql server firewall
      inputs:
        azureSubscription: ${{parameters.azureSubscription}}
        ScriptPath: 'content\sql-content\set-azure-firewall-rule.ps1'
        ScriptArguments: "-ServerName ${{ parameters.serverName }} -ResourceGroup ${{ parameters.resourceGroupName }}"
        azurePowerShellVersion: LatestVersion


    - task: CmdLine@1
      displayName: Run Sqlcmd
      inputs:
        filename: 'Sqlcmd'
        arguments: "-S ${{parameters.serverFqdn}} -U ${{parameters.userName}} -P ${{parameters.password}} -d ${{parameters.databaseName}} -i 'content\\sql-content\\database.sql'"

    - task: AzurePowerShell@5
      displayName: close sql server firewall
      inputs:
        azureSubscription: ${{parameters.azureSubscription}}
        ScriptPath: 'content\sql-content\remove-azure-firewall.ps1'
        ScriptArguments: "${{parameters.serverName}} -ResourceGroup ${{parameters.resourceGroupName}}"
        azurePowerShellVersion: LatestVersion



    
  #  - task: SqlAzureDacpacDeployment@1
  #    inputs:
  #      azureSubscription: ${{parameters.azureSubscription)
  #      ServerName: ${{parameters.serverName)
  #      DatabaseName: ${{parameters.databaseName)
  #      SqlUsername: ${{parameters.userName)
  #      SqlPassword: ${{parameters.password)
  #      DacpacFile: 'content\sql-content\proj-dev-sqldb-2022-4-21-17-56.bacpac'