apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
spec:
  type: {{ .Values.svc.type }} # Optional field (default)
  selector:
   app: {{ .Values.appSelector }}
  ports:
  - name: {{ .Values.ports.name }}
    protocol: {{ .Values.ports.protocol }}
    port: {{ .Values.svc.port }}
    targetPort: {{ .Values.ports.targetPort }}
