parameters:
- name: azureSubscription
  type: string
  #default: 'Azure subscription 1(2c02e9f9-7fad-4208-82e1-4e97500b5e0e)'
  
- name: aksclusterName
  type: string 
  #default: 'aks'

- name: useGrafana
  type: string
  default: true  
  
- name: dependsOn
  type: string
  default:  

- name: deploy
  type: boolean

- name: deployGrafana
  type: boolean  

stages:
- stage: Set_Aks_Permissions
  displayName: set aks cluster permissions to retrieve monitoring data
  dependsOn: ${{parameters.dependsOn}}

  jobs:
  - job: Set_Aks_Permissions
    condition: and ( eq('${{parameters.deployGrafana}}', 'True') , eq('${{parameters.deploy}}', 'True'))
    pool:
      vmImage: 'windows-latest'
    steps:
    #This task is responsible for giving the Aks the appropriate permissions, so the Azure-exporter project get the right permissions to access the monitor data in Azure, and can export it
      - task: AzureCLI@2
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }} 
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: |
            $aksInfo = $(az resource list --name ${{parameters.aksclusterName}}) | ConvertFrom-json
            $nodePoolInfo = $(az aks nodepool list --cluster-name $aksInfo.name --resource-group $aksInfo.resourceGroup) | ConvertFrom-json
            $backendInfo = az resource list --tag aks-managed-poolName=$($nodePoolInfo.name) | ConvertFrom-json
            $account = $(az account show) | ConvertFrom-Json 
            az vmss identity assign -g  $backendInfo.resourcegroup  -n $backendInfo.name --role "Monitoring Reader" --scope /subscriptions/$($account.id) 
            
