
stages:
- stage: Deploy_Infrastructure
  displayName: deploy Azure infrastructure
  variables:
    LOCATION: 'northeurope'
  jobs :
  - job: Deploy_Infrastructure
    variables:
    - template:  .\vars\vars.yml  
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription:  $(azureSubscription)
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: | 
          az deployment sub create  --template-file ''./main.bicep'' --location $LOCATION --parameters '{ \"aksRgName\": { \"value\": \"$(aksResourceGroupName)\" }, \"kubernetesVersion\": { \"value\": \"$(kubernetesVersion)\" } }'
      #  $  --parameters aksRgName="$(aksResourceGroupName)"\
      #  --parameters kubernetesVersion="$(kubernetesVersion)"\
      #   --parameters aksVmSize="$(aksVmSize)"\
      #    --parameters aksName="$(aksName)"
          
        # kubernetesVersion="$(kubernetesVersion)" aksVmSize="$(aksVmSize)" aksName="$(aksName)" aksRgName="$(aksResourceGroupName)" aksName=$aksName locationAks="$(locationAks)" aksNumberOfWorkers="$(aksNumberOfWorkers)" aksVmSize="$(aksVmSize)"