
stages:
- stage: Deploy_Infrastructure
  displayName: deploy Azure infrastructure
  variables:
  - template:  .\vars\vars.yml  
  jobs :
  - job: Deploy_Infrastructure
    variables:
        LOCATION: 'northeurope'
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription:  $(azureSubscription)
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: az deployment sub create  --template-file ''./main.bicep'' --location $LOCATION --parameters locationAks="$(locationAks)" aksNumberOfWorkers="$(aksNumberOfWorkers)" aksVmSize="$(aksVmSize)" aksRgName="$(aksResourceGroupName)" aksName="$(aksName)"
        # kubernetesVersion="$(kubernetesVersion)" aksVmSize="$(aksVmSize)" aksName="$(aksName)" aksRgName="$(aksResourceGroupName)"