
stages:
- stage: Deploy_Infrastructure
  displayName: deploy Azure infrastructure
  variables:
    LOCATION: 'northeurope'
  jobs :
  - job: Deploy_Infrastructure
    variables:
    - template:  .\vars\vars.yml  
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription:  $(azureSubscription)
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: | 
          echo '{ "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",' > main.parameters.json
          echo "\"contentVersion\": \"1.0.0.0\",">> main.parameters.json
          echo "\"parameters\": {">> main.parameters.json
          echo " \"kubernetesVersion\": { \"value\": \"$(kubernetesVersion)\" }, "  >> main.parameters.json
          echo " \"aksRgName\": { \"value\": \"$(aksResourceGroupName)\" } "  >> main.parameters.json
          echo "}}" >> main.parameters.json
          cat  main.parameters.json
          az deployment sub create  --template-file ''./main.bicep'' --location $LOCATION  --parameters  @main.parameters.json




      #--parameters '{ \"aksRgName\": { \"value\": \"$(aksResourceGroupName)\" }, \"kubernetesVersion\": { \"value\": \"$(kubernetesVersion)\" } }'
      #  $  --parameters aksRgName="$(aksResourceGroupName)"\
      #  --parameters kubernetesVersion="$(kubernetesVersion)"\
      #   --parameters aksVmSize="$(aksVmSize)"\
      #    --parameters aksName="$(aksName)"  
        # kubernetesVersion="$(kubernetesVersion)" aksVmSize="$(aksVmSize)" aksName="$(aksName)" aksRgName="$(aksResourceGroupName)" aksName=$aksName locationAks="$(locationAks)" aksNumberOfWorkers="$(aksNumberOfWorkers)" aksVmSize="$(aksVmSize)"

