
stages:
- stage: Deploy_Infrastructure
  displayName: deploy Azure infrastructure
  variables:
    LOCATION: 'northeurope'
  jobs :
  - job: Deploy_Infrastructure
    variables:
    - template:  .\vars\vars.yml  
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription:  $(azureSubscription)
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: | 
          echo '{ "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",' > main.parameters.json
          echo "\"contentVersion\": \"1.0.0.0\",">> main.parameters.json
          echo "\"parameters\": {">> main.parameters.json
          echo " \"kubernetesVersion\": { \"value\": \"$(kubernetesVersion)\" }, "  >> main.parameters.json
          echo " \"aksVmSize\": { \"value\": \"$(aksVmSize)\" }, "  >> main.parameters.json
          echo " \"aksName\": { \"value\": \"$(aksclusterName)\" }, "  >> main.parameters.json
          echo " \"aksRgName\": { \"value\": \"$(aksResourceGroupName)\" }, "  >> main.parameters.json
          echo " \"locationAks\": { \"value\": \"$(locationAks)\" }, "  >> main.parameters.json
          echo " \"aksNumberOfWorkers\": { \"value\": $(aksNumberOfWorkers) }, "  >> main.parameters.json
          echo " \"skuFunction\": { \"value\": \"$(skuFunction)\" }, "  >> main.parameters.json
          echo " \"skuCodeFunction\": { \"value\": \"$(skuCodeFunction)\" }, "  >> main.parameters.json
          echo " \"locationAzureFunction\": { \"value\": \"$(locationAzureFunction)\" }, "  >> main.parameters.json
          echo " \"azureFunctionRgName\": { \"value\": \"$(aksResourceGroupName)\" }, "  >> main.parameters.json
          echo " \"azureServicePlanFunction\": { \"value\": \"$(azureServicePlanFunction)\" }, "  >> main.parameters.json
          echo " \"numberOfWorkersFunction\": { \"value\": \"$(numberOfWorkersFunction)\" }, "  >> main.parameters.json
          echo " \"locationWebApp\": { \"value\": \"$(locationWebApp)\" }, "  >> main.parameters.json
          echo " \"skuCodeskuWebApp\": { \"value\": \"$(skuCodeskuWebApp)\" }, "  >> main.parameters.json
          echo " \"skuWebApp\": { \"value\": \"$(skuWebApp)\" }, "  >> main.parameters.json
          echo " \"numberOfWorkersWebApp\": { \"value\": \"$(numberOfWorkersWebApp)\" }, "  >> main.parameters.json
          echo " \"azureWebAppRgName\": { \"value\": \"$(appResourceGroupName)\" }, "  >> main.parameters.json
          echo " \"azureServicePlanWebApp\": { \"value\": \"$(azureServicePlanWebApp)\" }, "  >> main.parameters.json
          echo " \"sqlRgName\": { \"value\": \"$(sqlResourceGroupName)\" }, "  >> main.parameters.json
          echo " \"sqlDbName\": { \"value\": \"$(databaseName)\" }, "  >> main.parameters.json
          echo " \"SQL_User\": { \"value\": \"$(sqlUserName)\" }, "  >> main.parameters.json
          echo " \"SQL_Pass\": { \"value\": \"$(sqlPassword)\" }, "  >> main.parameters.json
          echo " \"locationSqlDatabase\": { \"value\": \"$(locationSqlDatabase)\" }, "  >> main.parameters.json
          echo " \"locationLogAnalytics\": { \"value\": \"$(locationLogAnalytics)\" }, "  >> main.parameters.json
          echo " \"azurekLogAnalyticsRgName\": { \"value\": \"$(azurekLogAnalyticsRgName)\" }, "  >> main.parameters.json
          echo " \"logAnalyticName\": { \"value\": \"$(logAnalyticName)\" }, "  >> main.parameters.json
          echo " \"deployAks\": { \"value\": \"$(deployAks)\" }, "  >> main.parameters.json
          echo " \"deployFunc\": { \"value\": \"$(deployFunc)\" }, "  >> main.parameters.json
          echo " \"deployApp\": { \"value\": \"$(deployApp)\" }, "  >> main.parameters.json
          echo " \"deploySql\": { \"value\": \"$(deploySql)\" }, "  >> main.parameters.json
          echo " \"projTagValue\": { \"value\": \"$(tagValue)\" } "  >> main.parameters.json
          echo "}}" >> main.parameters.json
          cat  main.parameters.json
          az deployment sub create  --template-file ''./main.bicep'' --location $LOCATION  --parameters  @main.parameters.json




      #--parameters '{ \"aksRgName\": { \"value\": \"$(aksResourceGroupName)\" }, \"kubernetesVersion\": { \"value\": \"$(kubernetesVersion)\" } }'
      #  $  --parameters aksRgName="$(aksResourceGroupName)"\
      #  --parameters kubernetesVersion="$(kubernetesVersion)"\
      #   --parameters aksVmSize="$(aksVmSize)"\
      #    --parameters aksName="$(aksName)"  
        # kubernetesVersion="$(kubernetesVersion)" aksVmSize="$(aksVmSize)" aksName="$(aksName)" aksRgName="$(aksResourceGroupName)" aksName=$aksName locationAks="$(locationAks)" aksNumberOfWorkers="$(aksNumberOfWorkers)" aksVmSize="$(aksVmSize)"

