parameters:
- name: azureSubscription
  type: string

- name: pythonVersion
  type: string

- name: dependsOn
  type: string
  default: ''  

- name: stageName
  type: string

- name: resourceGroup
  type: string

- name: aksUrl
  type: string
  default: "app.local"


stages:


- stage: Deploy_Webapp_Content
  displayName: push webapp code to azure webapp
  dependsOn : ${{ parameters.stageName }}
  pool:
    vmImage: 'ubuntu-latest'
  jobs :
    - job: Deploy_Webapp_Content
      variables:
        projectRoot: '$(System.DefaultWorkingDirectory)'
      steps:

        - download: current
          artifact: ${{ parameters.stageName }}

        - bash: |
            sudo apt-get install dos2unix -y
            dos2unix $(Pipeline.Workspace)/${{parameters.stageName}}/appName $(Pipeline.Workspace)/${{parameters.stageName}}/appName
            webAppName=$(cat $(Pipeline.Workspace)/${{parameters.stageName}}/appName)
            echo "##vso[task.setvariable variable=webAppName]$webAppName"


        - task: UsePythonVersion@0
          displayName: 'Use Python ${{parameters.pythonVersion}}'
          inputs:
            versionSpec: '${{parameters.pythonVersion}}'
        - script: |
            python -m venv antenv
            source antenv/bin/activate
            python -m pip install --upgrade pip
            pip install setup
            pip install -r requirements.txt
          workingDirectory: $(projectRoot)/content/webapp-content
          displayName: "Install requirements"

        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(projectRoot)/content/webapp-content'
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(webAppName)-$(Build.BuildId).zip
            replaceExistingArchive: true

        - upload: $(Build.ArtifactStagingDirectory)/$(webAppName)-$(Build.BuildId).zip
          displayName: 'Upload package'
          artifact: drop-webapp
        
        - task: AzureWebApp@1
          displayName: 'Deploy Azure Web App : webapppython43'
          inputs:
            azureSubscription: ${{parameters.azureSubscription}}
            appName: $(webAppName)
            package: $(Build.ArtifactStagingDirectory)/$(webAppName)-$(Build.BuildId).zip



- stage: Add_Webapp_Env_Vars
  displayName: push url env vars to azure webapp
  dependsOn : Deploy_Webapp_Content
  pool:
    vmImage: 'ubuntu-latest'
  jobs :
    - job: Add_Webapp_Env_Vars
      variables:
        projectRoot: '$(System.DefaultWorkingDirectory)'
      steps:
        - download: current
          artifact: ${{ parameters.stageName }}

        - bash: |
              sudo apt-get install dos2unix -y
              dos2unix $(Pipeline.Workspace)/${{parameters.stageName}}/funcUrl $(Pipeline.Workspace)/${{parameters.stageName}}/funcUrl
              dos2unix $(Pipeline.Workspace)/${{parameters.stageName}}/funcKey $(Pipeline.Workspace)/${{parameters.stageName}}/funcKey
              dos2unix $(Pipeline.Workspace)/${{parameters.stageName}}/fullyQualifiedDomainName $(Pipeline.Workspace)/${{parameters.stageName}}/fullyQualifiedDomainName
              dos2unix $(Pipeline.Workspace)/${{parameters.stageName}}/appName $(Pipeline.Workspace)/${{parameters.stageName}}/appName
              dos2unix $(Pipeline.Workspace)/${{parameters.stageName}}/aksIp $(Pipeline.Workspace)/${{parameters.stageName}}/aksIp
              fullyQualifiedDomainName=$(cat $(Pipeline.Workspace)/${{parameters.stageName}}/fullyQualifiedDomainName)
              funcUrl=$(cat $(Pipeline.Workspace)/${{parameters.stageName}}/funcUrl)
              funcKey=$(cat $(Pipeline.Workspace)/${{parameters.stageName}}/funcKey)
              aksIp=$(cat $(Pipeline.Workspace)/${{parameters.stageName}}/aksIp)
              webAppName=$(cat $(Pipeline.Workspace)/${{parameters.stageName}}/appName)
              echo "##vso[task.setvariable variable=fullyQualifiedDomainName]$fullyQualifiedDomainName"
              echo "##vso[task.setvariable variable=funcKey]$funcKey"
              echo "##vso[task.setvariable variable=funcUrl]$funcUrl"
              echo "##vso[task.setvariable variable=webAppName]$webAppName"
              echo "##vso[task.setvariable variable=aksIp]$aksIp"
              echo $funcKey

        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }} 
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az webapp config appsettings set -g ${{ parameters.resourceGroup }} -n $(webAppName) --settings "sql_url=$(fullyQualifiedDomainName)" "func_code=$(funcKey)" "func_url=$(funcUrl)" "aks_url=${{ parameters.aksUrl }}" "aks_ip=$(aksIp)"
