parameters:
- name: azureSubscription
  type: string

- name: pythonVersion
  type: string

- name: dependsOn
  type: string
  default: ''  

- name: stageName
  type: string

- name: resourceGroup
  type: string

- name: aksUrl
  type: string
  default: "app.local"

- name: deploy
  type: boolean


stages:


- stage: Deploy_Webapp_Content
  displayName: push webapp code to azure webapp
  dependsOn : ${{ parameters.stageName }}
  pool:
    vmImage: 'ubuntu-latest'
  jobs :
    - job: Deploy_Webapp_Content
      condition: eq({{parameters.deploy}}, ture)
      variables:
        projectRoot: '$(System.DefaultWorkingDirectory)'
      steps:

        - download: current
          artifact: ${{ parameters.stageName }}

        - bash: |
            sudo apt-get install dos2unix -y
            dos2unix $(Pipeline.Workspace)/${{parameters.stageName}}/appName $(Pipeline.Workspace)/${{parameters.stageName}}/appName
            webAppName=$(cat $(Pipeline.Workspace)/${{parameters.stageName}}/appName)
            echo "##vso[task.setvariable variable=webAppName]$webAppName"


        - task: UsePythonVersion@0
          displayName: 'Use Python ${{parameters.pythonVersion}}'
          inputs:
            versionSpec: '${{parameters.pythonVersion}}'
        - script: |
            python -m venv antenv
            source antenv/bin/activate
            python -m pip install --upgrade pip
            pip install setup
            pip install -r requirements.txt
          workingDirectory: $(projectRoot)/content/webapp-content
          displayName: "Install requirements"

        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(projectRoot)/content/webapp-content'
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(webAppName)-$(Build.BuildId).zip
            replaceExistingArchive: true

        - upload: $(Build.ArtifactStagingDirectory)/$(webAppName)-$(Build.BuildId).zip
          displayName: 'Upload package'
          artifact: drop-webapp


        - bash: |
            sleep 2m

        - task: AzureWebApp@1
          displayName: 'Deploy Azure Web App : webapppython43'
          inputs:
            azureSubscription: ${{parameters.azureSubscription}}
            appName: $(webAppName)
            package: $(Build.ArtifactStagingDirectory)/$(webAppName)-$(Build.BuildId).zip



